name: Add New PRs
on:
    pull_request:
        types:
            - opened
            - reopened
jobs:
    add-new-prs:
        runs-on: ubuntu-latest
        steps:
            - uses: alex-page/github-project-automation-plus@5bcba1c1c091a222584d10913e5c060d32c44044
              with:
                  project: Bytesurfers Tasks
                  column: In progress
                  repo-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}