name: Move Assigned Issues
on:
    issues:
        types:
            - assigned
jobs:
    move-assigned-issues:
        runs-on: ubuntu-latest
        steps:
            - uses: alex-page/github-project-automation-plus@5bcba1c1c091a222584d10913e5c060d32c44044
              with:
                  project: Bytesurfers Tasks
                  column: Staged
                  repo-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}